create schema if not exists raw;

CREATE TABLE raw.collision (
    collision_index text,
    collision_year smallint,
    collision_ref_no text,
    location_easting_osgr integer,
    location_northing_osgr integer,
    longitude double precision,
    latitude double precision,
    police_force smallint,
    collision_severity smallint,
    enhanced_collision_severity smallint,
    number_of_vehicles smallint,
    number_of_casualties smallint,
    date date,
    day_of_week smallint,
    time time,
    local_authority_district smallint,
    local_authority_ons_district text,
    local_authority_highway text,
    local_authority_highway_current text,
    first_road_class smallint,
    first_road_number smallint,
    road_type smallint,
    speed_limit smallint,
    junction_detail_historic smallint,
    junction_detail smallint,
    junction_control smallint,
    second_road_class smallint,
    second_road_number smallint,
    pedestrian_crossing_human_control_historic smallint,
    pedestrian_crossing_physical_facilities_historic smallint,
    pedestrian_crossing smallint,
    light_conditions smallint,
    weather_conditions smallint,
    road_surface_conditions smallint,
    special_conditions_at_site smallint,
    carriageway_hazards_historic smallint,
    carriageway_hazards smallint,
    urban_or_rural_area smallint,
    did_police_officer_attend_scene_of_collision smallint,
    did_police_officer_attend_scene_of_accident smallint,
    trunk_road_flag smallint,
    lsoa_of_collision_location text,
    lsoa_of_accident_location text,
    collision_injury_based smallint,
    collision_adjusted_serious double precision,
    collision_adjusted_slight double precision
);

CREATE TABLE raw.vehicle (
    collision_index text,
    collision_year smallint,
    collision_ref_no text,
    vehicle_reference text,
    vehicle_type smallint,
    towing_and_articulation smallint,
    vehicle_manoeuvre_historic smallint,
    vehicle_manoeuvre smallint,
    vehicle_direction_from smallint,
    vehicle_direction_to smallint,
    vehicle_location_restricted_lane_historic smallint,
    vehicle_location_restricted_lane smallint,
    junction_location smallint,
    skidding_and_overturning smallint,
    hit_object_in_carriageway smallint,
    vehicle_leaving_carriageway smallint,
    hit_object_off_carriageway smallint,
    first_point_of_impact smallint,
    vehicle_left_hand_drive smallint,
    journey_purpose_of_driver_historic smallint,
    journey_purpose_of_driver smallint,
    sex_of_driver smallint,
    age_of_driver smallint,
    age_band_of_driver smallint,
    engine_capacity_cc smallint,
    propulsion_code smallint,
    age_of_vehicle smallint,
    generic_make_model text,
    driver_imd_decile smallint,
    lsoa_of_driver text,
    escooter_flag smallint,
    driver_distance_banding smallint
);

CREATE TABLE raw.casualty (
    collision_index text,
    collision_year smallint,
    collision_ref_no text,
    vehicle_reference text,
    casualty_reference text,
    casualty_class smallint,
    sex_of_casualty smallint,
    age_of_casualty smallint,
    age_band_of_casualty smallint,
    casualty_severity smallint,
    enhanced_casualty_severity smallint,
    pedestrian_location smallint,
    pedestrian_movement smallint,
    car_passenger smallint,
    bus_or_coach_passenger smallint,
    pedestrian_road_maintenance_worker smallint,
    casualty_type smallint,
    casualty_imd_decile smallint,
    lsoa_of_casualty text,
    casualty_injury_based smallint,
    casualty_adjusted_serious double precision,
    casualty_adjusted_slight double precision,
    casualty_distance_banding smallint
);